Repository POSSF/POSSF, pull requests merged in 2021-07, with the labels that each got.

#18 Create Jekyll `pages` folder for better structure
  .github/workflows/invite-by-star.yml
  .github/workflows/lint.yml
  404.md
  _networks/MrMahmoudAhmadi.md
  _networks/ps-19.md
  pages/blog.md
  pages/contact.md
  pages/faq.html
  pages/network.md
  pages/privacy.md
  pages/register.md
  pages/speaker.md
  pages/sponsor.html
  pages/team.md
  pages/terms.md
  pages/workshop.md
Labels: bug, enhancement

#20 Create JafarRezaei.md
  _networks/JafarRezaei.md
Labels: documentation

#26 add iman-mirazimi image
  image/iman-mirazimi.jpg
Labels: documentation

#28 Run pre-commit
  404.md
  _networks/MrMahmoudAhmadi.md
  _speakers/2021-04-12-john-bampton.md
  test/asset/style.css
  test/asset/style2.css
  test/contact.html
  test/faq.html
  test/index.html
  test/person.html
  test/register.html
  test/speakers.html
  test/sponsor.html
  test/team.html
  test/workshop.html
  test/workshops.html
Labels: code style
